# BUILDING THE MODEL

# Importing Libraries

In [1]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import MaxPooling2D
from keras.layers import Conv2D
from keras.layers import Flatten

Using TensorFlow backend.
C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\tensorflo

# Initializing the model

In [2]:
model=Sequential()

# Adding all the req. layers

In [3]:
model.add(Conv2D(32,3,3,input_shape=(64,64,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(output_dim=128,activation='relu',init='random_uniform'))
model.add(Dense(output_dim=64,activation='relu',init='random_uniform'))
model.add(Dense(output_dim=32,activation='relu',init='random_uniform'))
model.add(Dense(output_dim=18,activation='relu',init='random_uniform'))
model.add(Dense(output_dim=9,activation='relu',init='random_uniform'))
model.add(Dense(output_dim=5,activation='softmax',init='random_uniform'))

C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(64, 64, 3..., activation="relu")`
  """Entry point for launching an IPython kernel.
C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128, kernel_initializer="random_uniform")`
  after removing the cwd from sys.path.
C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=64, kernel_initializer="random_uniform")`
  """
C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=32, kernel_initializer="random_uniform")`
  
C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\ipykernel_launcher.py:7: Use

# Summary of the layers added

In [4]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 30752)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               3936384   
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_3 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_4 (Dense)              (None, 18)                594       
__________

In [5]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [6]:
from keras.preprocessing.image import ImageDataGenerator

In [7]:
train_datagen=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
test_datagen=ImageDataGenerator(rescale=1./255)

# Getting the training & testing data in batches of 18

In [8]:
x_train=train_datagen.flow_from_directory(r"C:\Users\RAMKI ASMATH\Desktop\Skin_Disease\dataset\train_set",target_size=(64,64),batch_size=7,class_mode='sparse')

Found 1400 images belonging to 5 classes.


In [9]:
x_test=test_datagen.flow_from_directory(r"C:\Users\RAMKI ASMATH\Desktop\Skin_Disease\dataset\test_set",target_size=(64,64),batch_size=7,class_mode='sparse')

Found 329 images belonging to 5 classes.


In [10]:
print(x_train.class_indices)

{'actinic keratosis': 0, 'melanoma': 1, 'nevus': 2, 'pigmented benign keratosis': 3, 'vascular lesion': 4}


# Fitting the model 

In [11]:
model.fit_generator(x_train,samples_per_epoch=1400,epochs=60,validation_data=x_test,nb_val_samples=329)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
  """Entry point for launching an IPython kernel.
C:\Users\RAMKI ASMATH\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras_pre..., epochs=60, validation_data=<keras_pre..., steps_per_epoch=200, validation_steps=329)`
  """Entry point for launching an IPython kernel.


Epoch 1/60
200/200 [==============================] - 291s 1s/step - loss: 1.4808 - acc: 0.2971 - val_loss: 1.6446 - val_acc: 0.2432
Epoch 2/60
200/200 [==============================] - 261s 1s/step - loss: 1.4450 - acc: 0.2886 - val_loss: 1.5462 - val_acc: 0.2736
Epoch 3/60
200/200 [==============================] - 252s 1s/step - loss: 1.2980 - acc: 0.3843 - val_loss: 1.2885 - val_acc: 0.3495
Epoch 4/60
200/200 [==============================] - 249s 1s/step - loss: 1.1994 - acc: 0.4543 - val_loss: 1.2921 - val_acc: 0.4195: 7s -
Epoch 5/60
200/200 [==============================] - 251s 1s/step - loss: 1.1503 - acc: 0.4829 - val_loss: 1.2289 - val_acc: 0.4438
Epoch 6/60
200/200 [==============================] - 250s 1s/step - loss: 1.1404 - acc: 0.4943 - val_loss: 1.3504 - val_acc: 0.3799
Epoch 7/60
200/200 [==============================] - 252s 1s/step - loss: 1.1070 - acc: 0.5021 - val_loss: 1.2069 - val_acc: 0.4377
Epoch 8/60
200/200 [==============================] - 254s 1s/s

In [12]:
model.save('project-test.h5')

# PREDICTION

In [13]:
from keras.models import load_model
import numpy as np

In [14]:
import cv2

In [15]:
pred_model=load_model('project-test.h5')

In [16]:
from skimage.transform import resize

In [17]:
def detect(frame):
    try:
        img=resize(frame,(64,64))
        img=np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img=img/255.0
        prediction=model.predict(img)
        print(prediction)
        print(model.predict_classes(img))
    except AttributeError:
        print("Shape not found")
    
    

In [18]:
print(x_train.class_indices)

{'actinic keratosis': 0, 'melanoma': 1, 'nevus': 2, 'pigmented benign keratosis': 3, 'vascular lesion': 4}


In [19]:
frame=cv2.imread(r'C:\Users\RAMKI ASMATH\Desktop\Skin_Disease\dataset\test_set\actinic keratosis\ISIC_0030825.jpg')
data=detect(frame)

[[3.9544184e-02 1.6346291e-02 2.4968537e-02 9.1903806e-01 1.0293512e-04]]
[3]


In [20]:
frame3=cv2.imread(r'C:\Users\RAMKI ASMATH\Desktop\Skin_Disease\dataset\test_set\melanoma\ISIC_0000016.jpg')
data=detect(frame3)

[[2.8520408e-03 9.1552281e-01 6.0732890e-02 2.0889869e-02 2.3726795e-06]]
[1]


In [21]:
frame2=cv2.imread(r'C:\Users\RAMKI ASMATH\Desktop\Skin_Disease\dataset\test_set\nevus\ISIC_0000563.jpg')
data=detect(frame2)

[[4.8132286e-08 5.8841072e-02 9.3255341e-01 8.6054383e-03 5.6664302e-11]]
[2]


In [22]:
frame3=cv2.imread(r'C:\Users\RAMKI ASMATH\Desktop\Skin_Disease\dataset\test_set\pigmented benign keratosis\ISIC_0024324.jpg')
data=detect(frame3)

[[0.0373042  0.06457894 0.0508185  0.08375581 0.76354253]]
[4]


In [23]:
frame3=cv2.imread(r'C:\Users\RAMKI ASMATH\Desktop\Skin_Disease\dataset\test_set\vascular lesion\ISIC_0032890.jpg')
data=detect(frame3)

[[9.9634137e-03 1.8630803e-02 4.6637453e-02 9.2475814e-01 1.0097312e-05]]
[3]
